# Generated by Django 3.2.6 on 2021-08-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
